name: CI

on: [ push, pull_request ]

jobs:
  macos:
    runs-on: macos-latest
    env:
      LUA_VERSION: 5.4    
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          brew install lua boost postgis pandoc
          pip3 install psycopg2
          pg_ctl -D /usr/local/var/postgres start
        shell: bash

      - name: Setup database
        run: |
          psql -d postgres -c 'CREATE EXTENSION postgis'
          psql -d postgres -c 'CREATE EXTENSION hstore'
          psql -d postgres -c 'SELECT PostGIS_Full_Version()'
          mkdir -m 700 $GITHUB_WORKSPACE/tablespacetest
          psql -d postgres -c "CREATE TABLESPACE tablespacetest LOCATION '$GITHUB_WORKSPACE/tablespacetest'"
        shell: bash

      - uses: ./.github/actions/build-and-test
        with:
          test-wrapper: ''
        env:
          PGHOST: /tmp


  ubuntu18-pg95-gcc7-jit:
    runs-on: ubuntu-18.04

    env:
      CC: gcc-7
      CXX: g++-7
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 9.5
      POSTGIS_VERSION: 2.4
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu18-pg96-clang8-jit:
    runs-on: ubuntu-18.04

    env:
      CC: clang-8
      CXX: clang++-8
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 9.6
      POSTGIS_VERSION: 2.4
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu18-pg10-gcc9:
    runs-on: ubuntu-18.04

    env:
      CC: gcc-9
      CXX: g++-9
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 10
      POSTGIS_VERSION: 3
      CPP_VERSION: 14
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test


  ubuntu18-pg11-clang9:
    runs-on: ubuntu-18.04

    env:
      CC: clang-9
      CXX: clang++-9
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 11
      POSTGIS_VERSION: 2.5
      CPP_VERSION: 14
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu20-pg12-gcc10-jit:
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 12
      POSTGIS_VERSION: 2.5
      CPP_VERSION: 14
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test


  ubuntu20-pg13-clang10-jit:
    runs-on: ubuntu-20.04

    env:
      CC: clang-10
      CXX: clang++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 3
      CPP_VERSION: 14
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu20-pg13-clang10-proj6:
    runs-on: ubuntu-20.04

    env:
      CC: clang-10
      CXX: clang++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 3
      CPP_VERSION: 14
      USE_PROJ_LIB: 6
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu20-pg13-clang10-noproj:
    runs-on: ubuntu-20.04

    env:
      CC: clang-10
      CXX: clang++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 3
      CPP_VERSION: 14
      USE_PROJ_LIB: off
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu20-pg13-clang10-cpp17:
    runs-on: ubuntu-20.04

    env:
      CC: clang-10
      CXX: clang++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 14
      POSTGIS_VERSION: 3
      CPP_VERSION: 17
      USE_PROJ_LIB: 6
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  ubuntu20-pg13-gcc10-release:
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10
      LUA_VERSION: 5.3
      LUAJIT_OPTION: ON
      POSTGRESQL_VERSION: 13
      POSTGIS_VERSION: 2.5
      CPP_VERSION: 14
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/build-and-test

  windows-2019:
    runs-on: windows-2019
    env:
      GETOPT_INCLUDE_DIR: ${{ github.workspace }}/../wingetopt/src
      GETOPT_LIBRARY: ${{ github.workspace }}/../wingetopt/build/Release/wingetopt.lib
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/actions/win-install
      - uses: ./.github/actions/win-getopt
      - uses: ./.github/actions/win-cmake
      - uses: ./.github/actions/win-build
      - uses: ./.github/actions/win-test

  windows-2022:
    runs-on: windows-2022
    env:
      GETOPT_INCLUDE_DIR: ${{ github.workspace }}/../wingetopt/src
      GETOPT_LIBRARY: ${{ github.workspace }}/../wingetopt/build/Release/wingetopt.lib
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/actions/win-install
      - uses: ./.github/actions/win-getopt
      - uses: ./.github/actions/win-cmake
      - uses: ./.github/actions/win-build
      - uses: ./.github/actions/win-test

